spring:
  jpa: 
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://172.23.1.223:5432/playground
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver